name: Release to npm

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release to npm
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Node setup
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Dependencies
      run: yarn install --frozen-lockfile
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
